package com.trp.peloton.moshiobjects

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass


//import com.fasterxml.jackson.annotation.JsonProperty
@JsonClass(generateAdapter = true)
data class Ride(
    @field:Json(name = "captions")
    var captions: List<String?>,
    @field:Json(name = "class_type_ids")
    var classTypeIds: List<String?>?,
    @field:Json(name = "content_format")
    var contentFormat: String??,
    @field:Json(name = "content_provider")
    var contentProvider: String?,
    @field:Json(name = "description")
    var description: String?,
    @field:Json(name = "difficulty_estimate")
    var difficultyEstimate: Double?,
    @field:Json(name = "difficulty_level")
    var difficultyLevel: Any?,
    @field:Json(name = "difficulty_rating_avg")
    var difficultyRatingAvg: Double?,
    @field:Json(name = "difficulty_rating_count")
    var difficultyRatingCount: Int?,
    @field:Json(name = "duration")
    var duration: Int?,
    @field:Json(name = "equipment_ids")
    var equipmentIds: List<Any>?,
    @field:Json(name = "equipment_tags")
    var equipmentTags: List<Any>?,
    @field:Json(name = "excluded_platforms")
    var excludedPlatforms: List<Any>?,
    @field:Json(name = "extra_images")
    var extraImages: List<Any>?,
    @field:Json(name = "fitness_discipline")
    var fitnessDiscipline: String?,
    @field:Json(name = "fitness_discipline_display_name")
    var fitnessDisciplineDisplayName: String?,
    @field:Json(name = "has_closed_captions")
    var hasClosedCaptions: Boolean?,
    @field:Json(name = "has_free_mode")
    var hasFreeMode: Boolean?,
    @field:Json(name = "has_pedaling_metrics")
    var hasPedalingMetrics: Boolean?,
    @field:Json(name = "home_peloton_id")
    var homePelotonId: String?,
    @field:Json(name = "id")
    var id: String?,
    @field:Json(name = "image_url")
    var imageUrl: String?,
    @field:Json(name = "instructor_id")
    var instructorId: String?,
    @field:Json(name = "is_archived")
    var isArchived: Boolean?,
    @field:Json(name = "is_closed_caption_shown")
    var isClosedCaptionShown: Boolean?,
    @field:Json(name = "is_explicit")
    var isExplicit: Boolean?,
    @field:Json(name = "is_live_in_studio_only")
    var isLiveInStudioOnly: Boolean?,
    @field:Json(name = "language")
    var language: String?,
    @field:Json(name = "length")
    var length: Int?,
    @field:Json(name = "live_stream_id")
    var liveStreamId: String?,
    @field:Json(name = "live_stream_url")
    var liveStreamUrl: Any?,
    @field:Json(name = "location")
    var location: String?,
    @field:Json(name = "metrics")
    var metrics: List<String?>,
    @field:Json(name = "origin_locale")
    var originLocale: String?,
    @field:Json(name = "original_air_time")
    var originalAirTime: Int?,
    @field:Json(name = "overall_estimate")
    var overallEstimate: Double?,
    @field:Json(name = "overall_rating_avg")
    var overallRatingAvg: Double?,
    @field:Json(name = "overall_rating_count")
    var overallRatingCount: Int?,
    @field:Json(name = "pedaling_duration")
    var pedalingDuration: Int?,
    @field:Json(name = "pedaling_end_offset")
    var pedalingEndOffset: Int?,
    @field:Json(name = "pedaling_start_offset")
    var pedalingStartOffset: Int?,
    @field:Json(name = "rating")
    var rating: Int?,
    @field:Json(name = "ride_type_id")
    var rideTypeId: String?,
    @field:Json(name = "ride_type_ids")
    var rideTypeIds: List<String?>?,
    @field:Json(name = "sample_vod_stream_url")
    var sampleVodStreamUrl: Any?,
    @field:Json(name = "scheduled_start_time")
    var scheduledStartTime: Int?,
    @field:Json(name = "series_id")
    var seriesId: String?,
    @field:Json(name = "sold_out")
    var soldOut: Boolean?,
    @field:Json(name = "studio_peloton_id")
    var studioPelotonId: String?,
    @field:Json(name = "title")
    var title: String?,
    @field:Json(name = "total_in_progress_workouts")
    var totalInProgressWorkouts: Int?,
    @field:Json(name = "total_ratings")
    var totalRatings: Int?,
    @field:Json(name = "total_workouts")
    var totalWorkouts: Int?,
    @field:Json(name = "vod_stream_id")
    var vodStreamId: String?,
    @field:Json(name = "vod_stream_url")
    var vodStreamUrl: Any?
)