package com.trp.peloton.moshiobjects


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class UserData(
    @field:Json(name = "birthday")
    var birthday: Int,
    @field:Json(name = "block_explicit")
    var blockExplicit: Boolean,
    @field:Json(name = "can_charge")
    var canCharge: Boolean,
    @field:Json(name = "contract_agreements")
    var contractAgreements: List<ContractAgreement>,
    @field:Json(name = "created_at")
    var createdAt: Int,
    @field:Json(name = "created_country")
    var createdCountry: String,
    @field:Json(name = "customized_heart_rate_zones")
    var customizedHeartRateZones: List<Any>,
    @field:Json(name = "customized_max_heart_rate")
    var customizedMaxHeartRate: Int,
    @field:Json(name = "cycling_ftp")
    var cyclingFtp: Int,
    @field:Json(name = "cycling_ftp_source")
    var cyclingFtpSource: Any?,
    @field:Json(name = "cycling_ftp_workout_id")
    var cyclingFtpWorkoutId: Any?,
    @field:Json(name = "cycling_workout_ftp")
    var cyclingWorkoutFtp: Int,
    @field:Json(name = "default_heart_rate_zones")
    var defaultHeartRateZones: List<Double>,
    @field:Json(name = "default_max_heart_rate")
    var defaultMaxHeartRate: Int,
    @field:Json(name = "email")
    var email: String,
    @field:Json(name = "estimated_cycling_ftp")
    var estimatedCyclingFtp: Int,
    @field:Json(name = "facebook_access_token")
    var facebookAccessToken: String,
    @field:Json(name = "facebook_id")
    var facebookId: String,
    @field:Json(name = "first_name")
    var firstName: String,
    @field:Json(name = "gender")
    var gender: String,
    @field:Json(name = "has_active_device_subscription")
    var hasActiveDeviceSubscription: Boolean,
    @field:Json(name = "has_active_digital_subscription")
    var hasActiveDigitalSubscription: Boolean,
    @field:Json(name = "has_signed_waiver")
    var hasSignedWaiver: Boolean,
    @field:Json(name = "height")
    var height: Double,
    @field:Json(name = "id")
    var id: String,
    @field:Json(name = "image_url")
    var imageUrl: String,
    @field:Json(name = "instructor_id")
    var instructorId: Any?,
    @field:Json(name = "is_complete_profile")
    var isCompleteProfile: Boolean,
    @field:Json(name = "is_demo")
    var isDemo: Boolean,
    @field:Json(name = "is_external_beta_tester")
    var isExternalBetaTester: Boolean,
    @field:Json(name = "is_fitbit_authenticated")
    var isFitbitAuthenticated: Boolean,
    @field:Json(name = "is_internal_beta_tester")
    var isInternalBetaTester: Boolean,
    @field:Json(name = "is_profile_private")
    var isProfilePrivate: Boolean,
    @field:Json(name = "is_provisional")
    var isProvisional: Boolean,
    @field:Json(name = "is_strava_authenticated")
    var isStravaAuthenticated: Boolean,
    @field:Json(name = "last_name")
    var lastName: String,
    @field:Json(name = "last_workout_at")
    var lastWorkoutAt: Int,
    @field:Json(name = "location")
    var location: String,
    @field:Json(name = "member_groups")
    var memberGroups: List<String>,
    @field:Json(name = "middle_initial")
    var middleInitial: String,
    @field:Json(name = "name")
    var name: String,
    @field:Json(name = "obfuscated_email")
    var obfuscatedEmail: String,
    @field:Json(name = "paired_devices")
    var pairedDevices: List<PairedDevice>,
    @field:Json(name = "phone_number")
    var phoneNumber: String,
    @field:Json(name = "quick_hits")
    var quickHits: QuickHits,
    @field:Json(name = "referral_code")
    var referralCode: Any?,
    @field:Json(name = "referrals_made")
    var referralsMade: Int,
    @field:Json(name = "subscription_credits")
    var subscriptionCredits: Int,
    @field:Json(name = "subscription_credits_used")
    var subscriptionCreditsUsed: Int,
    @field:Json(name = "total_followers")
    var totalFollowers: Int,
    @field:Json(name = "total_following")
    var totalFollowing: Int,
    @field:Json(name = "total_non_pedaling_metric_workouts")
    var totalNonPedalingMetricWorkouts: Int,
    @field:Json(name = "total_pedaling_metric_workouts")
    var totalPedalingMetricWorkouts: Int,
    @field:Json(name = "total_pending_followers")
    var totalPendingFollowers: Int,
    @field:Json(name = "total_workouts")
    var totalWorkouts: Int,
    @field:Json(name = "username")
    var username: String,
    @field:Json(name = "v1_referrals_made")
    var v1ReferralsMade: Int,
    @field:Json(name = "weight")
    var weight: Double,
    @field:Json(name = "workout_counts")
    var workoutCounts: List<WorkoutCount>
)